version: '3.7'
services:
  caddy:
    container_name: bbl_caddy
    image: bbl_caddy:devel
    build: ./docker/caddy
    env_file:
      - ./docker/caddy/.env
    volumes:
      - ./docker/caddy/conf:/srv/caddy:delegated
      - ./docker/.dev/.caddy:/root/.caddy:delegated
      - ./docker/.dev/certs:/srv/certs:delegated
      - ./:/srv/www:delegated
    ports:
      - "80:80/tcp"
      - "443:443/tcp"

  postgres:
    container_name: bbl_postgres
    image: postgres:12-alpine
    env_file:
      - ./docker/postgres/.env
    volumes:
      - postgres_data.devel:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"

  django:
    container_name: bbl_django
    image: bbl_django:devel
    build:
      context: ./
      dockerfile: docker/django/Dockerfile
      target: django
    env_file:
      - ./.env
      - ./docker/django/.env
    volumes:
      - ./:/srv/app:delegated
      # Keep virtual environment out of Docker.
      - /srv/app/.venv
      # Keep node_modules out of Docker.
      - /srv/app/node_modules
    ports:
      - "8000:8000/tcp"
      - "8888:8888/tcp"
    stdin_open: true
    tty: true

  django-q:
    container_name: bbl_django-q
    image: bbl_django:devel
    build:
      context: ./
      dockerfile: docker/django/Dockerfile
      target: django
    env_file:
      - ./.env
      - ./docker/django/.env
    volumes:
      - ./:/srv/app:delegated
      # Keep node_modules out of Docker.
      - /srv/app/node_modules
    command: ["python", "-Wd", "manage.py", "qcluster"]

  webpack:
    container_name: bbl_webpack
    image: bbl_webpack:devel
    build:
      context: ./
      dockerfile: docker/webpack/Dockerfile
    env_file:
      - ./docker/webpack/.env
    volumes:
      - ./docker/.dev/.caddy:/root/.caddy:delegated
      - ./docker/.dev/certs:/srv/certs:cached
      - ./:/srv/app:cached
      # Keep node_modules out of Docker.
      - /srv/app/node_modules
    ports:
      - "55566:55566/tcp"

  maildev:
    container_name: bbl_maildev
    image: djfarrelly/maildev
    ports:
      - "1026:1026/tcp"
      - "1025:1025/tcp"
    command: ["bin/maildev", "--web", "1026", "--smtp", "1025"]

  es:
    container_name: bbl_es
    image: elasticsearch:7.17.22
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data.devel:/usr/share/elasticsearch/data

volumes:
  postgres_data.devel:
  es_data.devel:
