# Generated by Django 2.2.10 on 2020-12-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_squashed_0015_auto_20190816_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='biografía'),
        ),
    ]
