# Generated by Django 2.2.4 on 2019-08-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('search_engine', '0001_initial'), ('search_engine', '0002_auto_20190627_2052'), ('search_engine', '0003_indexedresource_need_to_index'), ('search_engine', '0004_auto_20190808_1644')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexed_at', models.DateTimeField(verbose_name='indexed at')),
                ('object_id', models.PositiveIntegerField()),
                ('need_to_index', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'recurso indexado',
                'verbose_name_plural': 'recursos indexados',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
