# Generated by Django 3.2.18 on 2024-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0001_squashed_0004_auto_20190808_1644"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indexedresource",
            index=models.Index(
                fields=["object_id"], name="search_engi_object__eb2416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexedresource",
            index=models.Index(
                fields=["need_to_index"], name="search_engi_need_to_87fdcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexedresource",
            index=models.Index(
                fields=["indexed_at"], name="search_engi_indexed_05bef6_idx"
            ),
        ),
    ]
