# Generated by Django 2.2.4 on 2019-08-27 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_squashed_0053_auto_20190816_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'invitado'), (-2, 'solicitado'), (1, 'colaborando')], help_text="Un usuario puede colaborar en una colección cuando su estado es 'colaborando'"),
        ),
        migrations.AlterField(
            model_name='collection',
            name='home_internal',
            field=models.BooleanField(default=False, help_text='Destaca la colección en el Home interno o listado de Colecciones.', verbose_name='Home interno'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='home_site',
            field=models.BooleanField(default=False, help_text='Muestra la Colección en el home principal del sitio.', verbose_name='Home principal'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(help_text='Una colección pública es visible por todos los usuarios del portal. Cuando no es pública, sólo el dueño la puede ver.', verbose_name='Colección pública'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='visible',
            field=models.BooleanField(default=True, help_text='Permite mostrar u ocultar la Colección en el sitio.'),
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='visible',
            field=models.BooleanField(default=True, help_text='Permite mostrar u ocultar un el recurso en el sitio.'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='address',
            field=models.TextField(blank=True, help_text='Dirección física de la fuente para acceso del público.', max_length=2000, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='contact',
            field=models.CharField(blank=True, help_text='Información de contacto de la fuente.', max_length=255, verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='exclusive',
            field=models.BooleanField(default=False, help_text='Marca una fuente como de acceso exclusivo de MegaRed. Los contenidos de fuentes exclusivas son accesible sólo por usuarios autenticados en MegaRed.', verbose_name='Exclusivo'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='is_ally',
            field=models.BooleanField(default=False, help_text="Marca la fuente como 'aliado'. Un aliado tiene mención especial en el sitio.", verbose_name='aliado'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='online_resources',
            field=models.BooleanField(default=False, help_text='Marca los contenidos de la fuente como de acceso digital.', verbose_name='acceso digital'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='parking',
            field=models.BooleanField(default=False, help_text='Información de parqueadero para el público en la fuente.', verbose_name='parqueadero'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='relevance',
            field=models.IntegerField(default=1, help_text='La relevancia de la fuente afecta el orden de los Recursos en algunos listados. Números menores aparecen de primero en los listados.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='relevancia'),
        ),
        migrations.AlterField(
            model_name='equivalence',
            name='icon_class',
            field=models.CharField(blank=True, choices=[('3d', '3d'), ('article', 'artículo'), ('audio', 'audio'), ('book', 'libro'), ('brochure', 'programa de mano (folleto)'), ('bulletin', 'boletin'), ('data', 'dato'), ('guide', 'guía de estudio'), ('interactive', 'interactivo'), ('map', 'mapa'), ('music-sheet', 'partitura'), ('newspaper', 'prensa'), ('objects', 'objeto físico'), ('picture', 'imágen'), ('series', 'serie monográfica'), ('software', 'software'), ('texts', 'texto'), ('thesis', 'tesis'), ('video', 'video')], help_text='Especifica el ícono a usar para los Recursos con equivalencia a este tipo de contenido. Sólo válido para `tipo de contenido`', max_length=50, null=True, verbose_name='clase de íconos'),
        ),
        migrations.AlterField(
            model_name='equivalence',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Especifica la prioridad de esta equivalencia. Números menores se muestran primero en los listados y filtros. Elementos sin prioridad se muestran de último.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='review_title',
            field=models.CharField(max_length=100, verbose_name='título de la reseña'),
        ),
        migrations.AlterField(
            model_name='exhibitionfeaturedcontentresource',
            name='position',
            field=models.PositiveSmallIntegerField(help_text='Especifica la posición en que se muestra este Recurso en el listado de destacados. Números menores se muestran primero.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='posición'),
        ),
        migrations.AlterField(
            model_name='historicalcollaborativecollection',
            name='home_internal',
            field=models.BooleanField(default=False, help_text='Destaca la colección en el Home interno o listado de Colecciones.', verbose_name='Home interno'),
        ),
        migrations.AlterField(
            model_name='historicalcollaborativecollection',
            name='home_site',
            field=models.BooleanField(default=False, help_text='Muestra la Colección en el home principal del sitio.', verbose_name='Home principal'),
        ),
        migrations.AlterField(
            model_name='historicalcollaborativecollection',
            name='public',
            field=models.BooleanField(help_text='Una colección pública es visible por todos los usuarios del portal. Cuando no es pública, sólo el dueño la puede ver.', verbose_name='Colección pública'),
        ),
        migrations.AlterField(
            model_name='historicalcollaborativecollection',
            name='visible',
            field=models.BooleanField(default=True, help_text='Permite mostrar u ocultar la Colección en el sitio.'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='home_internal',
            field=models.BooleanField(default=False, help_text='Destaca la colección en el Home interno o listado de Colecciones.', verbose_name='Home interno'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='home_site',
            field=models.BooleanField(default=False, help_text='Muestra la Colección en el home principal del sitio.', verbose_name='Home principal'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='public',
            field=models.BooleanField(help_text='Una colección pública es visible por todos los usuarios del portal. Cuando no es pública, sólo el dueño la puede ver.', verbose_name='Colección pública'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='visible',
            field=models.BooleanField(default=True, help_text='Permite mostrar u ocultar la Colección en el sitio.'),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='home_internal',
            field=models.BooleanField(default=False, help_text='Destaca la colección en el Home interno o listado de Colecciones.', verbose_name='Home interno'),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='home_site',
            field=models.BooleanField(default=False, help_text='Muestra la Colección en el home principal del sitio.', verbose_name='Home principal'),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='public',
            field=models.BooleanField(help_text='Una colección pública es visible por todos los usuarios del portal. Cuando no es pública, sólo el dueño la puede ver.', verbose_name='Colección pública'),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='review_title',
            field=models.CharField(max_length=100, verbose_name='título de la reseña'),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='visible',
            field=models.BooleanField(default=True, help_text='Permite mostrar u ocultar la Colección en el sitio.'),
        ),
        migrations.AlterField(
            model_name='promotedcontentresource',
            name='priority',
            field=models.PositiveSmallIntegerField(help_text='Especifica la prioridad de este Recurso. Números menores se muestran primero en los listados.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='set',
            name='home_internal',
            field=models.BooleanField(default=False, help_text='Destaca el Set en el home interno o listado de Sets.', verbose_name='Home interno'),
        ),
        migrations.AlterField(
            model_name='set',
            name='home_site',
            field=models.BooleanField(default=False, help_text='Muestra el Set en el home principal del sitio.', verbose_name='Home principal'),
        ),
        migrations.AlterField(
            model_name='set',
            name='visible',
            field=models.BooleanField(default=True, help_text='Permite mostrar u ocultar un Set y todos los Recursos de contenido asociados a este en el sitio. Un Recurso es visible cuando al menos uno de los Sets a los que pertenece es visible.'),
        ),
    ]
