# Generated by Django 2.2.4 on 2019-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_auto_20191003_1704'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('spec', 'data_source'), name='unique_spec_per_source'),
        ),
    ]
