# Generated by Django 2.2.4 on 2019-10-09 23:40
import os
import random

from django.conf import settings
from django.db import migrations, models


def add_detail_image_to_collections(apps, __):
    """Add detail image for existent collections and fill its history record."""
    Collection = apps.get_model("harvester", "Collection")

    for collection in Collection.objects.exclude(exhibition__isnull=False).iterator():
        collection.detail_image = get_image(collection)
        collection.save()


def get_image(instance):
    """Return a random image from the collection detail image folder."""
    non_static_path = os.path.join(settings.BASE_DIR, "resources", "static")
    return os.path.relpath(
        random.choice(
            list(
                set(dict(instance._meta.get_field("detail_image").formfield().choices))
            )
        ),
        non_static_path,
    )


class Migration(migrations.Migration):

    dependencies = [("harvester", "0005_auto_20191007_1146")]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="detail_image",
            field=models.FilePathField(
                match="\\.(jpg|jpeg|png|svg)$",
                null=True,
                path=os.path.join(
                    settings.BASE_DIR,
                    "resources",
                    "static",
                    "biblored",
                    "collections",
                    "detail_images",
                ),
                verbose_name="Imagen detalle de colección",
            ),
        ),
        migrations.AddField(
            model_name="historicalcollaborativecollection",
            name="detail_image",
            field=models.FilePathField(
                match="\\.(jpg|jpeg|png|svg)$",
                null=True,
                path=os.path.join(
                    settings.BASE_DIR,
                    "resources",
                    "static",
                    "biblored",
                    "collections",
                    "detail_images",
                ),
                verbose_name="Imagen detalle de colección",
            ),
        ),
        migrations.AddField(
            model_name="historicalcollection",
            name="detail_image",
            field=models.FilePathField(
                match="\\.(jpg|jpeg|png|svg)$",
                null=True,
                path=os.path.join(
                    settings.BASE_DIR,
                    "resources",
                    "static",
                    "biblored",
                    "collections",
                    "detail_images",
                ),
                verbose_name="Imagen detalle de colección",
            ),
        ),
        migrations.AddField(
            model_name="historicalexhibition",
            name="detail_image",
            field=models.FilePathField(
                match="\\.(jpg|jpeg|png|svg)$",
                null=True,
                path=os.path.join(
                    settings.BASE_DIR,
                    "resources",
                    "static",
                    "biblored",
                    "collections",
                    "detail_images",
                ),
                verbose_name="Imagen detalle de colección",
            ),
        ),
        migrations.RunPython(
            add_detail_image_to_collections, migrations.RunPython.noop
        ),
    ]
