# Generated by Django 2.2.4 on 2019-10-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0007_auto_20191022_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouphash',
            name='resource',
        ),
        migrations.AddField(
            model_name='collection',
            name='resources_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de recursos'),
        ),
        migrations.AddField(
            model_name='collection',
            name='resources_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='calculated_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='calculated_group_hash',
            field=models.TextField(editable=False, null=True, verbose_name='Hash de Agrupamiento'),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='calculation_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='collection_count_cached',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Número de colecciones'),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='collection_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='exhibition_count_cached',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Número de exhibiciones'),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='exhibition_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contentresource',
            name='force_calculation',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='contentresourceequivalence',
            name='resources_count_cached',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Número de recursos'),
        ),
        migrations.AddField(
            model_name='contentresourceequivalence',
            name='resources_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollaborativecollection',
            name='resources_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de recursos'),
        ),
        migrations.AddField(
            model_name='historicalcollaborativecollection',
            name='resources_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='resources_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de recursos'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='resources_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalexhibition',
            name='resources_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de recursos'),
        ),
        migrations.AddField(
            model_name='historicalexhibition',
            name='resources_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='resources_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de recursos'),
        ),
        migrations.AddField(
            model_name='set',
            name='resources_count_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='contentresource',
            index=models.Index(fields=['calculated_group_hash'], name='harvester_c_calcula_19c94d_idx'),
        ),
        migrations.DeleteModel(
            name='GroupHash',
        ),
    ]
