# Generated by Django 2.2.4 on 2019-11-27 22:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0009_auto_20191127_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='dynamic_image',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Imagen con URL Dinámica'),
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='collection_count_cached',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Número de colecciones'),
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='exhibition_count_cached',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Número de exhibiciones'),
        ),
        migrations.AlterField(
            model_name='contentresourceequivalence',
            name='resources_count_cached',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Número de recursos'),
        ),
    ]
