# Generated by Django 2.2.4 on 2019-12-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0010_auto_20191127_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='resources_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='collection_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de colecciones'),
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='collection_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='exhibition_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de exhibiciones'),
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='exhibition_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contentresourceequivalence',
            name='resources_count_cached',
            field=models.IntegerField(editable=False, null=True, verbose_name='Número de recursos'),
        ),
        migrations.AlterField(
            model_name='contentresourceequivalence',
            name='resources_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollaborativecollection',
            name='resources_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='resources_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='resources_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='resources_count_expired',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
    ]
