# Generated by Django 2.2.4 on 2019-12-11 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0011_auto_20191204_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='data_source_url',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace externo de la fuente'),
        ),
    ]
