# Generated by Django 2.2.8 on 2019-12-16 23:05

from django.db import migrations
import resources.fields
import resources.validators


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0012_set_data_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=resources.fields.WysiwygField(validators=[resources.validators.HtmlMaxLengthValidator(200)], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='review',
            field=resources.fields.WysiwygField(validators=[resources.validators.HtmlMaxLengthValidator(1800)], verbose_name='reseña'),
        ),
        migrations.AlterField(
            model_name='historicalcollaborativecollection',
            name='description',
            field=resources.fields.WysiwygField(validators=[resources.validators.HtmlMaxLengthValidator(200)], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='description',
            field=resources.fields.WysiwygField(validators=[resources.validators.HtmlMaxLengthValidator(200)], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='description',
            field=resources.fields.WysiwygField(validators=[resources.validators.HtmlMaxLengthValidator(200)], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='historicalexhibition',
            name='review',
            field=resources.fields.WysiwygField(validators=[resources.validators.HtmlMaxLengthValidator(1800)], verbose_name='reseña'),
        ),
    ]
