# Generated by Django 2.2.9 on 2019-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0015_auto_20191219_1228'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentresource',
            name='unique_resource_per_datasource',
        ),
        migrations.AddIndex(
            model_name='contentresource',
            index=models.Index(fields=['dynamic_identifier_cached', 'data_source'], name='harvester_c_dynamic_bf8029_idx'),
        ),
    ]
