# Generated by Django 2.2.9 on 2019-12-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0016_auto_20191227_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionfeaturedcontentresource',
            name='contentresource',
        ),
        migrations.RemoveField(
            model_name='exhibitionfeaturedcontentresource',
            name='exhibition',
        ),
        migrations.RemoveField(
            model_name='historicalexhibition',
            name='collection_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalexhibition',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalexhibition',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contentresource',
            name='exhibition_count_cached',
        ),
        migrations.RemoveField(
            model_name='contentresource',
            name='exhibition_count_expiration',
        ),
        migrations.RemoveField(
            model_name='contentresource',
            name='exhibition_count_expired',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
        migrations.DeleteModel(
            name='ExhibitionFeaturedContentResource',
        ),
        migrations.DeleteModel(
            name='HistoricalExhibition',
        ),
    ]
