# Generated by Django 2.2.10 on 2020-04-22 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0018_auto_20200107_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equivalence',
            options={'ordering': ['name', 'priority', '-updated_at'], 'verbose_name': 'equivalencia', 'verbose_name_plural': 'equivalencias'},
        ),
        migrations.AlterField(
            model_name='equivalence',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Especifica la prioridad de esta equivalencia. Números menores se muestran primero en los listados y filtros. Elementos sin prioridad se muestran de últimos.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='prioridad'),
        ),
    ]
