# Generated by Django 2.2.10 on 2020-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0020_auto_20200730_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborator",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="collectionandresource",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="contentresource",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="contentresourceequivalence",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="dynamicidentifierconfig",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="equivalence",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="historicalcollaborativecollection",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="historicalcollection",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="promotedcontentresource",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="set",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="setandresource",
            name="delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
    ]
