# Generated by Django 2.2.10 on 2021-01-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("harvester", "0024_auto_20210113_0800"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "delete",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Borrado programado"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SharedResourceUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "delete",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Borrado programado"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sharedresourceuser",
            name="shared_resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="harvester.SharedResource",
            ),
        ),
        migrations.AddField(
            model_name="sharedresourceuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="harvester.ContentResource",
            ),
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="shared_with",
            field=models.ManyToManyField(
                through="harvester.SharedResourceUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="compartido con",
            ),
        ),
        migrations.AddIndex(
            model_name="sharedresourceuser",
            index=models.Index(
                fields=["updated_at"], name="harvester_s_updated_495266_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedresource",
            index=models.Index(
                fields=["updated_at"], name="harvester_s_updated_8bc629_idx"
            ),
        ),
    ]
