# Generated by Django 2.2.10 on 2021-01-20 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harvester', '0025_auto_20210117_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedresource',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='sharedresource',
            name='harvester_s_updated_8bc629_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sharedresource',
            unique_together={('owner', 'resource')},
        ),
    ]
