# Generated by Django 2.2.10 on 2021-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0026_auto_20210120_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedresourceuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'no leído'), (1, 'leído'), (2, 'ignorado')], default=0),
        ),
    ]
