# Generated by Django 2.2.10 on 2021-01-21 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0027_sharedresourceuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='reseña'),
        ),
    ]
