# Generated by Django 2.2.10 on 2021-03-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0030_auto_20210125_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Colección institucional', 'verbose_name_plural': 'Colecciones institucionales'},
        ),
        migrations.RenameField(
            model_name='adminnotification',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='collaborator',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='collectionandresource',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='collectionsgroup',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='collectionsgroupcollection',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='contentresource',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='contentresourceequivalence',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='dynamicidentifierconfig',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='equivalence',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='historicalcollaborativecollection',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='historicalcollection',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='promotedcontentresource',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='setandresource',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='sharedresource',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RenameField(
            model_name='sharedresourceuser',
            old_name='delete',
            new_name='to_delete',
        )
    ]
