# Generated by Django 2.2.10 on 2021-04-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0031_auto_20210303_1755"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionsgroupcollection",
            options={},
        ),
        migrations.AddIndex(
            model_name="collectionsgroupcollection",
            index=models.Index(
                fields=["object_pk"], name="harvester_c_object__6b214c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionsgroupcollection",
            index=models.Index(
                fields=["content_type"], name="harvester_c_content_77a8d9_idx"
            ),
        ),
    ]
