# Generated by Django 2.2.10 on 2021-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0032_auto_20210417_0039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collaborativecollection",
            options={
                "base_manager_name": "objects",
                "verbose_name": "colección colaborativa",
                "verbose_name_plural": "colecciones colaborativas",
            },
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "default_manager_name": "objects",
                "ordering": ["-updated_at"],
                "verbose_name": "colección",
                "verbose_name_plural": "colecciones",
            },
        ),
    ]
