# Generated by Django 2.2.10 on 2021-06-23 22:19

from django.db import migrations


def convert_creator_to_equivalencerelation(apps, __):
    """Convierte los Autores a Equivalencias de Autor."""
    ContentResource = apps.get_model("harvester", "ContentResource")
    ContentResourceEquivalence = apps.get_model(
        "harvester", "ContentResourceEquivalence"
    )
    CreatorEquivalenceRelation = apps.get_model(
        "harvester", "CreatorEquivalenceRelation"
    )
    # Create Creators
    for resource in ContentResource.objects.iterator():
        if resource.creator is not None:
            for index, creator in enumerate(resource.creator):
                (
                    cr_equivalence,
                    created,
                ) = ContentResourceEquivalence.objects.get_or_create(
                    original_value=creator, field="creator"
                )
                creator_equivalence_relation = (
                    CreatorEquivalenceRelation.objects.get_or_create(
                        contentresourceequivalence_id=cr_equivalence.pk,
                        contentresource=resource,
                        position=index,
                    )
                )


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0035_auto_20210623_2218"),
    ]

    operations = [
        migrations.RunPython(
            convert_creator_to_equivalencerelation, migrations.RunPython.noop
        ),
    ]
