# Generated by Django 2.2.10 on 2021-06-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0036_convert_creator_to_equivalencerelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentresource",
            name="creator",
        ),
        migrations.AlterField(
            model_name="contentresourceequivalence",
            name="field",
            field=models.CharField(
                choices=[
                    ("type", "tipo de contenido"),
                    ("language", "idioma"),
                    ("rights", "derechos"),
                    ("subject", "tema"),
                ],
                max_length=255,
                verbose_name="campo",
            ),
        ),
        migrations.AlterField(
            model_name="equivalence",
            name="field",
            field=models.CharField(
                choices=[
                    ("type", "tipo de contenido"),
                    ("language", "idioma"),
                    ("rights", "derechos"),
                    ("subject", "tema"),
                ],
                max_length=255,
                verbose_name="campo",
            ),
        ),
    ]
