# Generated by Django 2.2.10 on 2021-06-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0037_auto_20210623_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentresource',
            old_name='creator_new',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='contentresourceequivalence',
            name='field',
            field=models.CharField(choices=[('type', 'tipo de contenido'), ('language', 'idioma'), ('rights', 'derechos'), ('subject', 'tema'), ('creator', 'autor')], max_length=255, verbose_name='campo'),
        ),
        migrations.AlterField(
            model_name='equivalence',
            name='field',
            field=models.CharField(choices=[('type', 'tipo de contenido'), ('language', 'idioma'), ('rights', 'derechos'), ('subject', 'tema'), ('creator', 'autor')], max_length=255, verbose_name='campo'),
        ),
    ]
