# Generated by Django 2.2.10 on 2021-10-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0039_auto_20211021_0318"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorequivalencerelation",
            name="to_delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="languageequivalencerelation",
            name="to_delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="rightsequivalencerelation",
            name="to_delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="subjectequivalencerelation",
            name="to_delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
        migrations.AddField(
            model_name="typeequivalencerelation",
            name="to_delete",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Borrado programado"
            ),
        ),
    ]
