# Generated by Django 2.2.10 on 2022-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0040_auto_20211023_0155"),
    ]

    operations = []
