# Generated by Django 3.2.18 on 2023-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0041_auto_20221006_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcollaborativecollection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical colección colaborativa', 'verbose_name_plural': 'historical colecciones colaborativas'},
        ),
        migrations.AlterModelOptions(
            name='historicalcollection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical colección', 'verbose_name_plural': 'historical colecciones'},
        ),
        migrations.AlterField(
            model_name='historicalcollaborativecollection',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
