# Generated by Django 3.2.18 on 2023-08-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0042_auto_20230403_1112'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentresource',
            index=models.Index(fields=['dynamic_identifier_expired'], name='harvester_c_dynamic_382e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='contentresource',
            index=models.Index(fields=['dynamic_identifier_expiration'], name='harvester_c_dynamic_1d3070_idx'),
        ),
        migrations.AddIndex(
            model_name='contentresource',
            index=models.Index(fields=['dynamic_identifier_expired', 'dynamic_identifier_expiration', 'data_source'],
                               name='harvester_c_dynamic_da64ae_idx'),
        ),
        migrations.AddIndex(
            model_name='contentresource',
            index=models.Index(fields=['dynamic_identifier_expired', 'dynamic_identifier_expiration'],
                               name='harvester_c_dynamic_5ae956_idx'),
        ),
    ]
