# Generated by Django 3.2.18 on 2024-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0043_auto_20230818_1418"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="setandresource",
            name="harvester_s_updated_46ccb8_idx",
        ),
        migrations.AddIndex(
            model_name="setandresource",
            index=models.Index(
                fields=["resource"], name="harvester_s_resourc_40fbfc_idx"
            ),
        ),
    ]
