# Generated by Django 4.2.13 on 2024-08-30 20:44

from django.db import migrations


def modified_old_spec_set(apps, schema_editor):
    ModelDatasource = apps.get_model("harvester", "DataSource")
    MyModel = apps.get_model("harvester", "Set")
    for row in MyModel.objects.all():
        # Obtiene datasource relacionado para verificar su config
        format_set = ModelDatasource.objects.filter(id=row.data_source_id).first()
        # Elimina el formato del spec en el set si lo contiene y lo actualiza
        new_spec_id = row.spec.replace(f'_{format_set.config["format"]}', "")
        row.spec = new_spec_id if format_set.config["format"] in row.spec else row.spec
        row.save(update_fields=["spec"])


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0044_auto_20240208_1357"),
    ]

    operations = [migrations.RunPython(modified_old_spec_set)]
