# Generated by Django 4.2.13 on 2024-10-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('harvester', '0046_harvest_stageharvest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='counter_total_resources',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Recursos en total'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='remaining_time',
            field=models.CharField(blank=True, default='0 d, 0 h, 0 m, 0 s', null=True, verbose_name='Restante estimado'),
        ),
    ]
