# Generated by Django 2.2.10 on 2020-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_red', '0001_squashed_0003_auto_20190710_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='delete',
            field=models.BooleanField(default=False, null=True, verbose_name='Borrado programado'),
        ),
    ]
