# Generated by Django 2.2.10 on 2021-03-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega_red', '0002_country_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='delete',
            new_name='to_delete',
        ),
    ]
