# Generated by Django 2.2.10 on 2021-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_red', '0003_auto_20210303_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='country',
            name='dian_code',
            field=models.IntegerField(verbose_name='código Dian'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=40, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
    ]
