# Generated by Django 2.2.9 on 2019-12-30 14:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0016_auto_20191227_1102'),
        ('expositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='subject',
            field=modelcluster.fields.ParentalManyToManyField(limit_choices_to={'field': 'subject'}, to='harvester.Equivalence'),
        ),
    ]
