# Generated by Django 2.2.9 on 2019-12-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0002_exposition_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='promoted',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '- No -'), (1, 'Home interno')], null=True, verbose_name='destacado'),
        ),
    ]
