# Generated by Django 2.2.9 on 2019-12-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0003_exposition_promoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposition',
            name='promoted',
        ),
        migrations.AddField(
            model_name='exposition',
            name='promoted_section',
            field=models.BooleanField(default=False, help_text='Muestra la Exposición en el home de exposiciones.', verbose_name='promover en sección'),
        ),
        migrations.AddField(
            model_name='exposition',
            name='promoted_site',
            field=models.BooleanField(default=False, help_text='Muestra la Exposición en el home principal del sitio.', verbose_name='promover en el home'),
        ),
    ]
