# Generated by Django 2.2.9 on 2019-12-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0017_auto_20191230_1340'),
        ('wagtailimages', '0001_squashed_0021'),
        ('expositions', '0004_auto_20191230_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouditem',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='clouditem',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='clouditem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='clouditem',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='clouditem',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'field': 'type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvester.Equivalence'),
        ),
    ]
