# Generated by Django 2.2.9 on 2020-02-08 02:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("harvester", "0018_auto_20200107_1455"),
        ("expositions", "0005_auto_20191231_0843"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("creator", models.TextField(blank=True, verbose_name="Autor")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.Image",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="harvester.ContentResource",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"field": "type"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="harvester.Equivalence",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.RemoveField(model_name="cloud", name="name"),
        migrations.AddField(
            model_name="cloud",
            name="subtitle",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Subtítulo",
            ),
        ),
        migrations.AddField(
            model_name="cloud",
            name="title",
            field=models.CharField(
                default=None, max_length=255, unique=True, verbose_name="Título"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cloud",
            name="group_by",
            field=models.CharField(
                choices=[
                    ("subject", "Tema"),
                    ("creator", "Autor"),
                    ("data_source", "Fuente de datos"),
                    ("date", "Fecha de publicación"),
                    ("type", "Formato"),
                ],
                max_length=15,
                verbose_name="Agrupar por",
            ),
        ),
        migrations.CreateModel(
            name="CloudResource",
            fields=[
                (
                    "resource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="expositions.Resource",
                    ),
                ),
                (
                    "cloud",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="expositions.Cloud",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("expositions.resource",),
        ),
        migrations.DeleteModel(name="CloudItem"),
    ]
