# Generated by Django 2.2.10 on 2020-03-09 15:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models

import resources.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('expositions', '0007_auto_20200221_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(verbose_name='Descripción Larga')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Título')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descripción Corta')),
                ('latitude', resources.fields.LatitudeField(decimal_places=6, max_digits=8)),
                ('longitude', resources.fields.LongitudeField(decimal_places=6, max_digits=9)),
                ('place', models.TextField(verbose_name='Lugar')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapMilestoneResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expositions.Resource')),
                ('milestone', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='expositions.MapMilestone')),
            ],
            options={
                'abstract': False,
            },
            bases=('expositions.resource',),
        ),
        migrations.CreateModel(
            name='TimelineMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Título')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descripción Corta')),
                ('long_description', models.TextField(max_length=300, verbose_name='Descripción Larga')),
                ('start_date', models.DateField(verbose_name='Fecha Inicial')),
                ('start_date_title', models.TextField(blank=True, max_length=60, null=True, verbose_name='Titulo Fecha Inicial')),
                ('start_place', models.TextField(blank=True, max_length=20, null=True, verbose_name='Lugar Inicial')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('end_date_title', models.TextField(blank=True, max_length=60, null=True, verbose_name='Titulo Fecha Final')),
                ('end_place', models.TextField(blank=True, max_length=20, null=True, verbose_name='Lugar Final')),
                ('category', models.CharField(choices=[('category_blue', 'Categoría 1 (Azul)'), ('category_magenta', 'Categoría 2 (Magenta)'), ('category_green', 'Categoría 3 (Verde)'), ('category_purple', 'Categoría 4 (Púrpura)'), ('category_yellow', 'Categoría 5 (Amarilla)'), ('category_red', 'Categoría 6 (Rojo)')], max_length=15, verbose_name='Categoría')),
                ('is_avatar', models.BooleanField(choices=[(True, 'Es una Persona')], default=False, verbose_name='Es una Persona')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeLineMilestoneResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expositions.Resource')),
                ('milestone', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='expositions.TimelineMilestone')),
            ],
            options={
                'abstract': False,
            },
            bases=('expositions.resource',),
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='timeline',
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Mapa', 'verbose_name_plural': 'Mapas'},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'Linea de Tiempo', 'verbose_name_plural': 'Lineas de Tiempo'},
        ),
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='name',
        ),
        migrations.AddField(
            model_name='exposition',
            name='theme',
            field=models.TextField(choices=[('magenta', 'Magenta'), ('purple', 'Púrpura'), ('blue', 'Azul')], default='magenta', help_text='Personaliza la apariencia de la exposición cambiando el color del tema.', verbose_name='Color de la Plantilla'),
        ),
        migrations.AddField(
            model_name='map',
            name='center_at_latitude',
            field=resources.fields.LatitudeField(decimal_places=6, default=0, max_digits=8, verbose_name='Latitud Inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='center_at_longitude',
            field=resources.fields.LongitudeField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitud Inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Imagen de Fondo'),
        ),
        migrations.AddField(
            model_name='map',
            name='max_zoom_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=20, verbose_name='Zoom Máximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='min_zoom_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=0, verbose_name='Zoom Mínimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='category_blue',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción Categoría Azul'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='category_green',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción Categoría Verde'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='category_magenta',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción Categoría Magenta'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='category_purple',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción Categoría Púrpura'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='category_red',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción Categoría Roja'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='category_yellow',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción Categoría Amarilla'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='title',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date_group_by',
            field=models.CharField(choices=[('Y', 'Año'), ('M', 'Año-Mes'), ('D', 'Año-Mes-Dia')], default='Y', max_length=1, verbose_name='Tipo de Fecha'),
        ),
        migrations.DeleteModel(
            name='MapPoint',
        ),
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
        migrations.AddField(
            model_name='timelinemilestone',
            name='timeline',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='expositions.Timeline'),
        ),
        migrations.AddField(
            model_name='mapmilestone',
            name='map',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='expositions.Map'),
        ),
        migrations.AddField(
            model_name='mapmilestone',
            name='pin_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Icono del Pin'),
        ),
    ]
