# Generated by Django 2.2.10 on 2020-03-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('harvester', '0018_auto_20200107_1455'),
        ('expositions', '0009_auto_20200313_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='expositionsection',
            name='rich_text_intro',
            field=models.TextField(blank=True, help_text='Introdución corta que se muestra si la sección de contenido inicia con un texto enriquecido.', max_length=200, null=True, verbose_name='Introducción de Texto Enriquecido'),
        ),
        migrations.AddField(
            model_name='expositionsection',
            name='rich_text_title',
            field=models.TextField(blank=True, help_text='Encabezado que se muestra si la sección de contenido inicia con un texto enriquecido.', max_length=150, null=True, verbose_name='Titulo de Texto Enriquecido'),
        ),
        migrations.AddField(
            model_name='redirection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.RemoveField(
            model_name='expositionsection',
            name='subject',
        ),
        migrations.AddField(
            model_name='expositionsection',
            name='subject',
            field=models.ForeignKey(limit_choices_to={'field': 'subject'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='harvester.Equivalence'),
        ),
    ]
