# Generated by Django 2.2.10 on 2020-04-01 13:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0012_auto_20200327_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
