# Generated by Django 2.2.10 on 2020-04-17 13:41

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0013_auto_20200401_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposition',
            options={'verbose_name': 'exposición', 'verbose_name_plural': 'exposiciones'},
        ),
        migrations.AlterField(
            model_name='mapmilestone',
            name='long_description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
