# Generated by Django 2.2.10 on 2020-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0014_auto_20200417_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
