# Generated by Django 2.2.10 on 2020-04-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0015_auto_20200417_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='harvester.ContentResource', verbose_name='Recurso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelinemilestone',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fechas menores a 1950 se deben escribir manualmente usando el formato aaaa-mm-dd', null=True, verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='timelinemilestone',
            name='start_date',
            field=models.DateField(help_text='Fechas menores a 1950 se deben escribir manualmente usando el formato aaaa-mm-dd', verbose_name='Fecha Inicial'),
        ),
    ]
