# Generated by Django 2.2.10 on 2020-04-22 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0016_auto_20200422_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=models.ForeignKey(limit_choices_to={'setandresource__isnull': False, 'visible': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='harvester.ContentResource', verbose_name='Recurso'),
        ),
    ]
