# Generated by Django 2.2.10 on 2020-05-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0018_auto_20200505_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloud',
            options={'verbose_name': 'Nube de Términos', 'verbose_name_plural': 'Nubes de Términos'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Galería de Imágenes', 'verbose_name_plural': 'Galerías de Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='narrative',
            options={'verbose_name': 'Narrativa', 'verbose_name_plural': 'Narrativas'},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'verbose_name': 'Galería de Videos', 'verbose_name_plural': 'Galerías de Videos'},
        ),
    ]
