# Generated by Django 2.2.10 on 2020-07-09 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expositions.editors
import resources.validators
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0020_auto_20200625_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expositionsection',
            options={'verbose_name': 'Sección de exposición', 'verbose_name_plural': 'Secciones de exposición'},
        ),
        migrations.RemoveField(
            model_name='timelinemilestone',
            name='end_date_title',
        ),
        migrations.RemoveField(
            model_name='timelinemilestone',
            name='start_date_title',
        ),
        migrations.AddField(
            model_name='timelinemilestone',
            name='subtitle_1',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Subtítulo 1'),
        ),
        migrations.AddField(
            model_name='timelinemilestone',
            name='subtitle_2',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Subtítulo 2'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='description',
            field=wagtail.fields.RichTextField(validators=[resources.validators.HtmlMaxLengthValidator(300)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, validators=[resources.validators.HtmlMaxLengthValidator(150)], verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='subject',
            field=models.ForeignKey(limit_choices_to={'field': 'subject'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='harvester.Equivalence', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='expositionsection',
            name='content',
            field=wagtail.fields.StreamField([('wysiwyg', expositions.editors.FullEditor()), ('image_gallery', wagtail.snippets.blocks.SnippetChooserBlock('expositions.ImageGallery', label='Galería de Imágenes')), ('video_gallery', wagtail.snippets.blocks.SnippetChooserBlock('expositions.VideoGallery', label='Galería de Vídeos')), ('map', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Map', label='Mapa')), ('cloud', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Cloud', label='Nube de Términos')), ('timeline', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Timeline', label='Línea de Tiempo')), ('narrative', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Narrative', label='Narrativa'))], verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='expositionsection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='expositionsection',
            name='subject',
            field=models.ForeignKey(limit_choices_to={'field': 'subject'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='harvester.Equivalence', verbose_name='Tema'),
        ),
    ]
