# Generated by Django 2.2.10 on 2020-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0021_auto_20200709_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinemilestone',
            name='end_date_title',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Titulo Fecha Final'),
        ),
        migrations.AddField(
            model_name='timelinemilestone',
            name='start_date_title',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Titulo Fecha Inicial'),
        ),
    ]
