# Generated by Django 2.2.10 on 2020-07-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0022_auto_20200716_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelinemilestone',
            options={'ordering': ['start_date'], 'verbose_name': 'Hito de Linea de Tiempo', 'verbose_name_plural': 'Hitos de Linea de Tiempo'},
        ),
    ]
