# Generated by Django 2.2.10 on 2020-09-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0023_auto_20200730_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='expositionsection',
            name='show_context_delimiter',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='group_by',
            field=models.CharField(choices=[('subject', 'Tema'), ('creator', 'Autor'), ('data_source', 'Fuente de datos'), ('date', 'Año de publicación'), ('type', 'Formato')], max_length=15, verbose_name='Agrupar por'),
        ),
    ]
