# Generated by Django 2.2.10 on 2020-12-11 14:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0028_auto_20201209_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposition',
            name='related_expositions',
            field=wagtail.fields.StreamField([('exposition', wagtail.blocks.PageChooserBlock('expositions.exposition', icon='form', label='Exposición', max_num=4))], blank=True, null=True, verbose_name='Exposiciones Relacionadas'),
        ),
        migrations.AlterField(
            model_name='expositionsection',
            name='related_expositions',
            field=wagtail.fields.StreamField([('exposition', wagtail.blocks.PageChooserBlock('expositions.exposition', icon='form', label='Exposición', max_num=4))], blank=True, null=True, verbose_name='Exposiciones Relacionadas'),
        ),
    ]
