# Generated by Django 2.2.10 on 2020-12-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0029_auto_20201211_0937'),
        ('expositions', '0027_auto_20201214_1011'),
    ]

    operations = [
    ]
