# Generated by Django 2.2.10 on 2021-04-17 00:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0034_auto_20210112_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposition',
            name='related_expositions',
            field=wagtail.fields.StreamField([('exposition', wagtail.blocks.PageChooserBlock('expositions.Exposition', icon='form', label='Exposición', max_num=4))], blank=True, null=True, verbose_name='Exposiciones Relacionadas'),
        ),
    ]
