# Generated by Django 2.2.10 on 2021-06-23 22:17

from django.db import migrations
import resources.validators
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0035_auto_20210417_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposition',
            name='description',
            field=wagtail.fields.RichTextField(max_length=320, validators=[resources.validators.HtmlMaxLengthValidator(300)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, max_length=170, validators=[resources.validators.HtmlMaxLengthValidator(150)], verbose_name='Introducción'),
        ),
    ]
