# Generated by Django 2.2.10 on 2021-11-02 13:57

from django.db import migrations
import instance_selector.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0037_map_milestones_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='milestones_content',
            field=wagtail.fields.StreamField([('time_line_milestone', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Título', max_length=60)), ('short_description', wagtail.blocks.TextBlock(label='Descripción Corta', max_length=300)), ('long_description', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'superscript', 'subscript', 'blockquote'], label='Descripción Larga')), ('publish_date', wagtail.blocks.DateBlock(label='Fecha de Publicación', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('start_date', wagtail.blocks.DateBlock(help_text='Fechas menores a 1950 se deben escribir manualmente usando el formato aaaa-mm-dd', label='Fecha Inicial')), ('start_date_title', wagtail.blocks.TextBlock(label='Titulo Fecha Inicial', max_length=60, required=False)), ('start_place', wagtail.blocks.TextBlock(label='Lugar Inicial', max_length=20, required=False)), ('subtitle_1', wagtail.blocks.TextBlock(label='Subtítulo 1', max_length=60, required=False)), ('subtitle_2', wagtail.blocks.TextBlock(label='Subtítulo 2', max_length=60, required=False)), ('end_date', wagtail.blocks.DateBlock(help_text='Fechas menores a 1950 se deben escribir manualmente usando el formato aaaa-mm-dd', label='Fecha Final', required=False)), ('end_date_title', wagtail.blocks.TextBlock(label='Titulo Fecha Final', max_length=60, required=False)), ('end_place', wagtail.blocks.TextBlock(label='Lugar Final', max_length=20, required=False)), ('category', wagtail.blocks.ChoiceBlock(choices=[('category_blue', 'Categoría 1 (Azul)'), ('category_magenta', 'Categoría 2 (Magenta)'), ('category_green', 'Categoría 3 (Verde)'), ('category_purple', 'Categoría 4 (Púrpura)'), ('category_yellow', 'Categoría 5 (Amarilla)'), ('category_red', 'Categoría 6 (Rojo)')], label='Categoría')), ('is_avatar', wagtail.blocks.BooleanBlock(label='Es una Persona', required=False)), ('resources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('resource', instance_selector.blocks.InstanceSelectorBlock(label='Recurso', target_model='harvester.contentresource')), ('title', wagtail.blocks.TextBlock(label='Título', required=False)), ('description', wagtail.blocks.TextBlock(label='Descripción', required=False)), ('creator', wagtail.blocks.TextBlock(label='Autor', required=False)), ('date', wagtail.blocks.DateBlock(label='Fecha', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('type', instance_selector.blocks.InstanceSelectorBlock(label='Tipo', required=False, target_model='harvester.equivalence'))]), label='Recursos'))]))], default=list, verbose_name='Hitos de Mapa'),
        ),
        migrations.AlterField(
            model_name='map',
            name='milestones_content',
            field=wagtail.fields.StreamField([('map_milestone', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Título', max_length=60)), ('short_description', wagtail.blocks.TextBlock(label='Descripción Corta', max_length=300)), ('long_description', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'superscript', 'subscript', 'blockquote'], label='Descripción Larga')), ('publish_date', wagtail.blocks.DateBlock(label='Fecha de Publicación', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('latitude', wagtail.blocks.DecimalBlock(decimal_places=6, label='Latitud', max_digits=8, max_value=90, min_value=-90)), ('longitude', wagtail.blocks.DecimalBlock(decimal_places=6, label='Longitud', max_digits=9, max_value=180, min_value=-180)), ('place', wagtail.blocks.TextBlock(label='Lugar')), ('pin_image', wagtail.images.blocks.ImageChooserBlock(label='Icono del Pin', required=False)), ('resources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('resource', instance_selector.blocks.InstanceSelectorBlock(label='Recurso', target_model='harvester.contentresource')), ('title', wagtail.blocks.TextBlock(label='Título', required=False)), ('description', wagtail.blocks.TextBlock(label='Descripción', required=False)), ('creator', wagtail.blocks.TextBlock(label='Autor', required=False)), ('date', wagtail.blocks.DateBlock(label='Fecha', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('type', instance_selector.blocks.InstanceSelectorBlock(label='Tipo', required=False, target_model='harvester.equivalence'))]), label='Recursos'))]))], default=list, verbose_name='Hitos de Mapa'),
        ),
    ]
