# Generated by Django 2.2.10 on 2021-11-03 21:43

from django.db import migrations


def convert_milestone_from_snippet_to_block(apps, schema_editor):
    """Convert Old Milestone Snippet to StreamField Content."""

    Map = apps.get_model("expositions", "map")
    for mapa in Map.objects.iterator():
        print("\nConvirtiendo Hitos de Mapa: ", mapa.title, " ID:", mapa.pk)
        new_milestones = []
        for milestone in mapa.milestones.iterator():
            milestone_block = {
                "type": "map_milestone",
                "value": {
                    "title": milestone.title,
                    "short_description": milestone.short_description,
                    "long_description": milestone.long_description,
                    "publish_date": milestone.publish_date,
                    "image": milestone.image_id,
                    "latitude": milestone.latitude,
                    "longitude": milestone.longitude,
                    "place": milestone.place,
                    "pin_image": milestone.pin_image_id,
                    "resources": [],
                },
            }
            for resource in milestone.resources.iterator():
                milestone_block["value"]["resources"].append(
                    {
                        "resource": resource.resource_id,
                        "title": resource.title,
                        "description": resource.description,
                        "creator": resource.creator,
                        "date": resource.date,
                        "image": resource.image_id,
                        "type": resource.type_id,
                    }
                )

            new_milestones.append(milestone_block)
        mapa.milestones_content.stream_data = new_milestones
        mapa.save()


class Migration(migrations.Migration):

    dependencies = [
        ("expositions", "0038_auto_20211102_1357"),
    ]

    operations = [
        migrations.RunPython(
            convert_milestone_from_snippet_to_block,
            migrations.RunPython.noop,
        )
    ]
