# Generated by Django 2.2.10 on 2022-10-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expositions", "0040_auto_20211104_0102"),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        )
    ]
