# Generated by Django 2.2.10 on 2022-10-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expositions", "0044_homepage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainsPassModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, null=True, verbose_name="Nombre"),
                ),
                (
                    "domain",
                    models.URLField(max_length=256, null=True, verbose_name="Dominio"),
                ),
            ],
            options={
                "verbose_name": "Dominio",
                "verbose_name_plural": "Dominios",
            },
        ),
    ]
