# Generated by Django 2.2.10 on 2022-10-19 19:14

from django.db import migrations, models
import django.db.models.deletion
import expositions.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('expositions', '0045_domainspassmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', expositions.fields.ContentStreamField(blank=True, null=True, verbose_name='Contenido')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.search.index.Indexed),
        ),
    ]
