# Generated by Django 2.2.10 on 2022-11-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0049_auto_20221102_1739'),
        ('expositions', '0048_auto_20221101_0940'),
    ]

    operations = [
    ]
