# Generated by Django 2.2.10 on 2022-11-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0050_merge_20221121_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del tipo de exposición')),
            ],
            options={
                'verbose_name': 'Tipo de exposición',
                'verbose_name_plural': 'Tipos de exposición',
            },
        ),
    ]
