# Generated by Django 2.2.10 on 2022-11-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0051_typeexposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='exposition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expositions.TypeExposition'),
        ),
    ]
