# Generated by Django 2.2.10 on 2022-11-22 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0052_exposition_exposition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposition',
            name='exposition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expositions.TypeExposition', verbose_name='Tipo de exposición'),
        ),
    ]
