# Generated by Django 2.2.10 on 2022-11-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0050_merge_20221109_0957'),
        ('expositions', '0053_auto_20221122_1845'),
    ]

    operations = [
    ]
