# Generated by Django 2.2.10 on 2022-12-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expositions", "0055_auto_20221214_1602"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tooltip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(
                        help_text="Texto que aparece en el Tooltip seleccionado",
                        verbose_name="Texto Tooltip",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("simple_search", "Búsqueda simple"),
                            ("advanced_search", "Búsqueda avanzada"),
                            ("collection_groups", "Grupos de las colecciones"),
                            (
                                "collection_groups_creation",
                                "Crear grupo de colecciones",
                            ),
                            ("favorites", "Colecciones favoritas"),
                            ("collection_creation", "Crear colección"),
                            ("exposition_timeline", "Exposiciones linea del tiempo"),
                            ("exposition_map", "Exposiciones mapa"),
                            ("login", "Registro y login"),
                            ("profile_image", "Perfil: foto recorte de imágenes"),
                        ],
                        max_length=255,
                        verbose_name="Tooltip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tooltip",
                "verbose_name_plural": "Tooltips",
            },
        ),
    ]
