# Generated by Django 2.2.10 on 2023-01-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0057_tooltip'),
        ('expositions', '0056_auto_20221223_1122'),
    ]

    operations = [
    ]
