# Generated by Django 2.2.10 on 2023-01-03 16:37

from django.db import migrations, models
import expositions.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0058_merge_20230103_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpage',
            name='footer_content',
            field=expositions.fields.ContentStreamField(blank=True, null=True, verbose_name='Contenido Footer'),
        ),
        migrations.AlterField(
            model_name='tooltip',
            name='description',
            field=wagtail.fields.RichTextField(max_length=255, verbose_name='Texto Tooltip'),
        ),
        migrations.AlterField(
            model_name='tooltip',
            name='page',
            field=models.CharField(choices=[('simple_search', 'Búsqueda simple'), ('advanced_search', 'Búsqueda avanzada'), ('collection_groups', 'Grupos de las colecciones'), ('collection_groups_creation', 'Crear grupo de colecciones'), ('favorites', 'Colecciones favoritas'), ('collection_creation', 'Crear colección'), ('exposition_timeline', 'Exposiciones linea del tiempo'), ('exposition_map', 'Exposiciones mapa'), ('login', 'Registro y login'), ('profile_image', 'Perfil: foto recorte de imágenes')], max_length=255, verbose_name='Página'),
        ),
    ]
