# Generated by Django 2.2.10 on 2023-01-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0059_auto_20230103_1137'),
        ('expositions', '0041_domain_by_pass_model'),
    ]

    operations = [
    ]
