# Generated by Django 3.2.18 on 2023-05-10 15:01

from django.db import migrations
import expositions.edit_handlers
import expositions.editors
import expositions.fields
import expositions.models.components
import instance_selector.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0061_auto_20230504_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=expositions.fields.ContentStreamField(blank=True, null=True, use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='related_expositions',
            field=wagtail.fields.StreamField([('exposition', wagtail.blocks.PageChooserBlock('expositions.Exposition', icon='form', label='Exposición', max_num=4))], blank=True, null=True, use_json_field=True, verbose_name='Exposiciones Relacionadas'),
        ),
        migrations.AlterField(
            model_name='expositionsection',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=150, required=False, verbose_name='Titulo')), ('intro', wagtail.blocks.TextBlock(max_length=200, required=False, verbose_name='Introducción')), ('show_context_delimiter', wagtail.blocks.BooleanBlock(default=True, help_text='muestra una línea delimitadora antes de este componente.', label='Mostrar delimitador de contexto', null=True, required=False)), ('wysiwyg', expositions.editors.FullEditor())])), ('image_gallery', wagtail.snippets.blocks.SnippetChooserBlock('expositions.ImageGallery', label='Galería de Imágenes')), ('video_gallery', wagtail.snippets.blocks.SnippetChooserBlock('expositions.VideoGallery', label='Galería de Vídeos')), ('map', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Map', label='Mapa')), ('cloud', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Cloud', label='Nube de Términos')), ('timeline', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Timeline', label='Línea de Tiempo')), ('narrative', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Narrative', label='Narrativa')), ('avatar_list', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Título de Sección')), ('type', wagtail.blocks.ChoiceBlock(choices=[('text', 'Sin imágenes'), ('image', 'Con imágenes')], label='Visualización')), ('avatar_list', wagtail.blocks.StreamBlock([('user', wagtail.blocks.StructBlock([('user', wagtailmodelchooser.blocks.ModelChooserBlock(label='Seleccione un usuario del sistema', required=True, target_model='custom_user.user')), ('subtitle', wagtail.blocks.CharBlock(help_text='Recuerda no colocar un subtítulo de más de 50 caracteres', label='Cargo o subtítulo del avatar', max_length=50, required=True)), ('extra_info', wagtail.blocks.CharBlock(help_text='Recuerda no colocar información adicional del avatar de más de 50 caracteres', label='Información adicional del avatar', max_length=50, required=False))])), ('custom_user', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(help_text='Recuerda no colocar un subtítulo de más de 50 caracteres', label='Nombre o título del avatar', max_length=50, required=True)), ('subtitle', wagtail.blocks.CharBlock(help_text='Recuerda no colocar un subtítulo de más de 50 caracteres', label='Cargo o subtítulo del avatar', max_length=50, required=True)), ('extra_info', wagtail.blocks.CharBlock(help_text='Recuerda no colocar información adicional del avatar de más de 50 caracteres', label='Información adicional del avatar', max_length=50, required=False)), ('url', wagtail.blocks.URLBlock(help_text='Puedes agregar al avatar un link externo', required=False))]))], help_text='Selecciona el tipo Usuario del Sistema si deseas traer un usuario de la Bibliteca Digital de Bogota, de lo contrario puedes crear un avatar desde cero ', label='Tipos de usuario')), ('info', expositions.editors.LimitedEditor(label='Subsección de información', required=False))])), ('section_list', wagtail.blocks.StructBlock([('show_context_delimiter', wagtail.blocks.BooleanBlock(default=True, help_text='Muestra una línea delimitadora antes de este componente.', label='Mostrar delimitador de contexto', null=True, required=False)), ('title', wagtail.blocks.CharBlock(label='Título de Sección', required=False)), ('intro', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'blockquote', 'underline', 'bold', 'italic', 'superscript', 'subscript', 'link'], label='Texto introductorio', required=False)), ('image_group_list', wagtail.blocks.ListBlock(expositions.models.components.ImageGroupComponent, label='Grupos de Imágenes')), ('closure', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'blockquote', 'underline', 'bold', 'italic', 'superscript', 'subscript', 'link'], label='Texto de cierre', required=False))])), ('link_to_content_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('links', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(help_text='Página de contenido', label='Página', page_type=['expositions.ContentPage', 'expositions.Redirection', 'expositions.Exposition', 'expositions.HelpCenterPage', 'expositions.QuestionPage', 'expositions.ThemePage']), help_text='Páginas de contenido a las que enlazar', label='Enlaces', max_num=4, min_num=1))]))], use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='expositionsection',
            name='related_expositions',
            field=wagtail.fields.StreamField([('exposition', wagtail.blocks.PageChooserBlock('expositions.exposition', icon='form', label='Exposición', max_num=4))], blank=True, null=True, use_json_field=True, verbose_name='Exposiciones Relacionadas'),
        ),
        migrations.AlterField(
            model_name='helpcenterpage',
            name='content',
            field=expositions.fields.HelpCenterStreamField(blank=True, null=True, use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=expositions.fields.HomeStreamField(blank=True, null=True, use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=expositions.fields.HeroStreamField(blank=True, null=True, use_json_field=True, verbose_name='Banner Hero'),
        ),
        migrations.AlterField(
            model_name='map',
            name='milestones_content',
            field=wagtail.fields.StreamField([('map_milestone', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Título', max_length=60)), ('short_description', wagtail.blocks.TextBlock(label='Descripción Corta', max_length=300)), ('long_description', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'superscript', 'subscript', 'blockquote'], label='Descripción Larga')), ('publish_date', wagtail.blocks.DateBlock(label='Fecha de Publicación', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('latitude', wagtail.blocks.DecimalBlock(decimal_places=6, label='Latitud', max_digits=8, max_value=90, min_value=-90)), ('longitude', wagtail.blocks.DecimalBlock(decimal_places=6, label='Longitud', max_digits=9, max_value=180, min_value=-180)), ('place', wagtail.blocks.TextBlock(label='Lugar')), ('pin_image', wagtail.images.blocks.ImageChooserBlock(label='Icono del Pin', required=False)), ('resources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('resource', instance_selector.blocks.InstanceSelectorBlock(icon='doc-full-inverse', label='Recurso', target_model='harvester.contentresource')), ('title', wagtail.blocks.TextBlock(label='Título', required=False)), ('description', wagtail.blocks.TextBlock(label='Descripción', required=False)), ('creator', wagtail.blocks.TextBlock(label='Autor', required=False)), ('date', wagtail.blocks.DateBlock(label='Fecha', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('type', instance_selector.blocks.InstanceSelectorBlock(icon='clipboard-list', label='Tipo', required=False, target_model='harvester.equivalence'))]), label='Recursos'))]))], default=list, use_json_field=True, verbose_name='Hitos de Mapa'),
        ),
        migrations.AlterField(
            model_name='narrativeresource',
            name='related_text',
            field=wagtail.fields.StreamField([('related_text', expositions.editors.MiniEditor())], use_json_field=True, verbose_name='Texto Relacionado'),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='content',
            field=expositions.fields.ContentStreamField(blank=True, null=True, use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='footer_content',
            field=expositions.fields.ContentStreamField(blank=True, null=True, use_json_field=True, verbose_name='Contenido Footer'),
        ),
        migrations.AlterField(
            model_name='themepage',
            name='content',
            field=expositions.fields.ContentStreamField(blank=True, null=True, use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='milestones_content',
            field=wagtail.fields.StreamField([('time_line_milestone', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Título', max_length=60)), ('short_description', wagtail.blocks.TextBlock(label='Descripción Corta', max_length=300)), ('long_description', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'superscript', 'subscript', 'blockquote'], label='Descripción Larga')), ('publish_date', wagtail.blocks.DateBlock(label='Fecha de Publicación', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('start_date', wagtail.blocks.DateBlock(help_text='Fechas menores a 1950 se deben escribir manualmente usando el formato aaaa-mm-dd', label='Fecha Inicial')), ('start_date_title', wagtail.blocks.TextBlock(label='Titulo Fecha Inicial', max_length=60, required=False)), ('start_place', wagtail.blocks.TextBlock(label='Lugar Inicial', max_length=20, required=False)), ('subtitle_1', wagtail.blocks.TextBlock(label='Subtítulo 1', max_length=60, required=False)), ('subtitle_2', wagtail.blocks.TextBlock(label='Subtítulo 2', max_length=60, required=False)), ('end_date', wagtail.blocks.DateBlock(help_text='Fechas menores a 1950 se deben escribir manualmente usando el formato aaaa-mm-dd', label='Fecha Final', required=False)), ('end_date_title', wagtail.blocks.TextBlock(label='Titulo Fecha Final', max_length=60, required=False)), ('end_place', wagtail.blocks.TextBlock(label='Lugar Final', max_length=20, required=False)), ('category', wagtail.blocks.ChoiceBlock(choices=[('category_blue', 'Categoría 1 (Azul)'), ('category_magenta', 'Categoría 2 (Magenta)'), ('category_green', 'Categoría 3 (Verde)'), ('category_purple', 'Categoría 4 (Púrpura)'), ('category_yellow', 'Categoría 5 (Amarilla)'), ('category_red', 'Categoría 6 (Rojo)')], label='Categoría')), ('is_avatar', wagtail.blocks.BooleanBlock(label='Es una Persona', required=False)), ('resources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('resource', instance_selector.blocks.InstanceSelectorBlock(icon='doc-full-inverse', label='Recurso', target_model='harvester.contentresource')), ('title', wagtail.blocks.TextBlock(label='Título', required=False)), ('description', wagtail.blocks.TextBlock(label='Descripción', required=False)), ('creator', wagtail.blocks.TextBlock(label='Autor', required=False)), ('date', wagtail.blocks.DateBlock(label='Fecha', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=False)), ('type', instance_selector.blocks.InstanceSelectorBlock(icon='clipboard-list', label='Tipo', required=False, target_model='harvester.equivalence'))]), label='Recursos'))]))], default=list, use_json_field=True, verbose_name='Hitos de lineas de tiempo'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='videos',
            field=wagtail.fields.StreamField([('video', expositions.edit_handlers.VideoBlock(label='video'))], use_json_field=True),
        ),
    ]
