# Generated by Django 3.2.18 on 2023-05-11 15:14

from django.db import migrations, models
import django.db.models.deletion
import expositions.blocks
import expositions.editors
import expositions.models.components
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0063_auto_20230510_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expositionsection',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=150, required=False, verbose_name='Titulo')), ('intro', wagtail.blocks.TextBlock(max_length=200, required=False, verbose_name='Introducción')), ('show_context_delimiter', wagtail.blocks.BooleanBlock(default=True, help_text='muestra una línea delimitadora antes de este componente.', label='Mostrar delimitador de contexto', null=True, required=False)), ('wysiwyg', expositions.editors.FullEditor())])), ('image_gallery', wagtail.snippets.blocks.SnippetChooserBlock('expositions.ImageGallery', label='Galería de Imágenes')), ('video_gallery', wagtail.snippets.blocks.SnippetChooserBlock('expositions.VideoGallery', label='Galería de Vídeos')), ('map', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Map', label='Mapa')), ('cloud', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Cloud', label='Nube de Términos')), ('timeline', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Timeline', label='Línea de Tiempo')), ('narrative', wagtail.snippets.blocks.SnippetChooserBlock('expositions.Narrative', label='Narrativa')), ('avatar_list', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Título de Sección')), ('type', wagtail.blocks.ChoiceBlock(choices=[('text', 'Sin imágenes'), ('image', 'Con imágenes')], label='Visualización')), ('avatar_list', wagtail.blocks.StreamBlock([('user', wagtail.blocks.StructBlock([('user', expositions.blocks.UserChooserBlock(label='Seleccione un usuario del sistema', required=True)), ('subtitle', wagtail.blocks.CharBlock(help_text='Recuerda no colocar un subtítulo de más de 50 caracteres', label='Cargo o subtítulo del avatar', max_length=50, required=True)), ('extra_info', wagtail.blocks.CharBlock(help_text='Recuerda no colocar información adicional del avatar de más de 50 caracteres', label='Información adicional del avatar', max_length=50, required=False))])), ('custom_user', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(help_text='Recuerda no colocar un subtítulo de más de 50 caracteres', label='Nombre o título del avatar', max_length=50, required=True)), ('subtitle', wagtail.blocks.CharBlock(help_text='Recuerda no colocar un subtítulo de más de 50 caracteres', label='Cargo o subtítulo del avatar', max_length=50, required=True)), ('extra_info', wagtail.blocks.CharBlock(help_text='Recuerda no colocar información adicional del avatar de más de 50 caracteres', label='Información adicional del avatar', max_length=50, required=False)), ('url', wagtail.blocks.URLBlock(help_text='Puedes agregar al avatar un link externo', required=False))]))], help_text='Selecciona el tipo Usuario del Sistema si deseas traer un usuario de la Bibliteca Digital de Bogota, de lo contrario puedes crear un avatar desde cero ', label='Tipos de usuario')), ('info', expositions.editors.LimitedEditor(label='Subsección de información', required=False))])), ('section_list', wagtail.blocks.StructBlock([('show_context_delimiter', wagtail.blocks.BooleanBlock(default=True, help_text='Muestra una línea delimitadora antes de este componente.', label='Mostrar delimitador de contexto', null=True, required=False)), ('title', wagtail.blocks.CharBlock(label='Título de Sección', required=False)), ('intro', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'blockquote', 'underline', 'bold', 'italic', 'superscript', 'subscript', 'link'], label='Texto introductorio', required=False)), ('image_group_list', wagtail.blocks.ListBlock(expositions.models.components.ImageGroupComponent, label='Grupos de Imágenes')), ('closure', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'blockquote', 'underline', 'bold', 'italic', 'superscript', 'subscript', 'link'], label='Texto de cierre', required=False))])), ('link_to_content_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('links', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(help_text='Página de contenido', label='Página', page_type=['expositions.ContentPage', 'expositions.Redirection', 'expositions.Exposition', 'expositions.HelpCenterPage', 'expositions.QuestionPage', 'expositions.ThemePage']), help_text='Páginas de contenido a las que enlazar', label='Enlaces', max_num=4, min_num=1))]))], use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='expositionsection',
            name='subject',
            field=models.ForeignKey(limit_choices_to={'field': 'subject'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='harvester.subjectequivalence', verbose_name='Tema'),
        ),
    ]
