# Generated by Django 3.2.18 on 2023-05-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositions', '0064_auto_20230511_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='exposition',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='expositionsection',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='helpcenterpage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='questionpage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='redirection',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Palabras clave'),
        ),
    ]
