# Generated by Django 2.2.10 on 2021-05-06 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0003_auto_20190703_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistuseragent',
            name='user_agent',
            field=models.CharField(max_length=255, unique=True, verbose_name='navegador'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='hitcount',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hitcount.HitCount', verbose_name='contenido visitado'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='user_agent',
            field=models.CharField(editable=False, max_length=255, verbose_name='navegador'),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='visitas'),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificada el'),
        ),
    ]
